language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly

install:
  - composer install --no-interaction --prefer-dist
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then
      wget -O ./vendor/bin/phpunit https://phar.phpunit.de/phpunit-5.phar
      chmod +x ./vendor/bin/phpunit
    elif [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then
      wget -O ./vendor/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
      chmod +x ./vendor/bin/phpunit
    fi

before_script:
  # Remove XDebug for better performance.
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi

script:
  - ./vendor/bin/phpunit Tests
