language: php
jobs:
  include:
   - php: 5.6
   - php: 5.5
     dist: precise
   - php: 5.4
     dist: precise
   - php: 5.3
     dist: precise
   - php: hhvm
sudo: false
install:
  - composer install --dev
script: vendor/phpunit/phpunit/phpunit Tests
