language: php
jobs:
  include:
   - php: 7.2
   - php: 7.1
   - php: 7.0
   - php: 5.6
   - php: 5.5
     dist: precise
   - php: 5.4
     dist: precise
   - php: hhvm
sudo: false
dist: trusty
install:
  - composer install --dev
script: vendor/phpunit/phpunit/phpunit Tests
matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
